"""empty message

Revision ID: 4fc2c1bb34f3
Revises: 
Create Date: 2017-12-26 12:54:13.182752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fc2c1bb34f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentor', sa.Column('blog', sa.String(length=255), nullable=True))
    op.add_column('mentor', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('mentor', sa.Column('fbprofile', sa.String(length=255), nullable=True))
    op.add_column('mentor', sa.Column('gitprofile', sa.String(length=255), nullable=True))
    op.add_column('mentor', sa.Column('linkedinprofile', sa.String(length=255), nullable=True))
    op.add_column('mentor', sa.Column('slack_team', sa.String(length=255), nullable=True))
    op.drop_column('mentor', 'available')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentor', sa.Column('available', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('mentor', 'slack_team')
    op.drop_column('mentor', 'linkedinprofile')
    op.drop_column('mentor', 'gitprofile')
    op.drop_column('mentor', 'fbprofile')
    op.drop_column('mentor', 'email')
    op.drop_column('mentor', 'blog')
    # ### end Alembic commands ###
